src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EventRepository::class)]
class Event
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;

    #[ORM\Column]
    private ?int $capacity = null;

    #[ORM\Column(length: 255)]
    private ?string $address = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_start_time = null;

    #[ORM\Column(length: 100)]
    private ?string $email = null;

    #[ORM\Column(type: Types::BIGINT)]
    private ?string $phone_number = null;

    #[ORM\ManyToOne(inversedBy: 'type')]
    #[ORM\JoinColumn(nullable: false)]
    private ?TypeOfEvent $typeOfEvent = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getCapacity(): ?int
    {
        return $this->capacity;
    }

    public function setCapacity(int $capacity): static
    {
        $this->capacity = $capacity;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): static
    {
        $this->address = $address;

        return $this;
    }

    public function getDateStartTime(): ?\DateTimeInterface
    {
        return $this->date_start_time;
    }

    public function setDateStartTime(\DateTimeInterface $date_start_time): static
    {
        $this->date_start_time = $date_start_time;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(string $phone_number): static
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getTypeOfEvent(): ?TypeOfEvent
    {
        return $this->typeOfEvent;
    }

    public function setTypeOfEvent(?TypeOfEvent $typeOfEvent): static
    {
        $this->typeOfEvent = $typeOfEvent;

        return $this;
    }
}

src/Entity/TypeOfEvent.php
<?php

namespace App\Entity;

use App\Repository\TypeOfEventRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TypeOfEventRepository::class)]
class TypeOfEvent
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    /**
     * @var Collection<int, Event>
     */
    #[ORM\OneToMany(targetEntity: Event::class, mappedBy: 'typeOfEvent')]
    private Collection $type;

    #[ORM\Column(length: 100)]
    private ?string $event_type = null;

    public function __construct()
    {
        $this->type = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection<int, Event>
     */
    public function getType(): Collection
    {
        return $this->type;
    }

    public function addType(Event $type): static
    {
        if (!$this->type->contains($type)) {
            $this->type->add($type);
            $type->setTypeOfEvent($this);
        }

        return $this;
    }

    public function removeType(Event $type): static
    {
        if ($this->type->removeElement($type)) {
            // set the owning side to null (unless already changed)
            if ($type->getTypeOfEvent() === $this) {
                $type->setTypeOfEvent(null);
            }
        }

        return $this;
    }

    public function getEventType(): ?string
    {
        return $this->event_type;
    }

    public function setEventType(string $event_type): static
    {
        $this->event_type = $event_type;

        return $this;
    }
}

src/Form/EventType.php
<?php

namespace App\Form;

use App\Entity\Event;
use App\Entity\TypeOfEvent;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EventType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                'attr' => ['class' => 'form-control'],
            ])
            ->add('description', TextareaType::class, [
                'attr' => ['class' => 'form-control'],
            ])
            ->add('image', TextType::class, [
                'attr' => ['class' => 'form-control'],
            ])
            ->add('capacity', NumberType::class, [
                'attr' => [
                    'class' => 'form-control',
                    'inputmode' => 'tel',
                    'pattern' => '^\+?[1-9]\d{1,14}$',
                    'oninput' => "this.value = this.value.replace(/[^0-9+]/g, '')",
                    'maxlength' => 6,
                ],
                'scale' => 2,
            ])
            ->add('address', TextType::class, [
                'attr' => ['class' => 'form-control'],
            ])
            ->add('date_start_time', DateTimeType::class, [
                'date_label' => 'Starts On',
                'attr' => ['class' => 'form-control'],
                'label' => 'Event Date and Time'
            ])
            ->add('email', EmailType::class, [
                'attr' => ['class' => 'form-control'],
            ])
            ->add('phone_number', TextType::class, [
                'attr' => [
                    'class' => 'form-control',
                    'inputmode' => 'tel',
                    'pattern' => '^\+?[1-9]\d{1,14}$',
                    'oninput' => "this.value = this.value.replace(/[^0-9+]/g, '')",
                    'maxlength' => 15,
                ],
            ])
            ->add('typeOfEvent', EntityType::class, [
                // looks for choices from this entity
                'class' => TypeOfEvent::class,

                // uses the User.username property as the visible option string
                'choice_label' => 'event_type',
                'attr' => ['class' => 'form-control'],
                'placeholder' => 'Select an event type',

                // used to render a select box, check boxes or radios
                // 'multiple' => true,
                // 'expanded' => true,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Event::class,
        ]);
    }
}

src/Controller/EventController.php
<?php

namespace App\Controller;

use App\Entity\Event;
use App\Form\EventType;
use App\Repository\EventRepository;
use App\Repository\TypeOfEventRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/event')]
class EventController extends AbstractController
{
    #[Route('/', name: 'app_event_index', methods: ['GET'])]
    public function index(EventRepository $eventRepository, TypeOfEventRepository $typeOfEventRepository, Request $request): Response
    {
        $typeId = $request->query->get('type');

        if ($typeId) {
            $events = $eventRepository->findBy(['typeOfEvent' => $typeId]);
        } else {
            $events = $eventRepository->findAll();
        }
        $types = $typeOfEventRepository->findAll();

        return $this->render('event/index.html.twig', [
            'events' => $events,
            'types' => $types,
        ]);
    }

    #[Route('/new', name: 'app_event_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $event = new Event();
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($event);
            $entityManager->flush();

            return $this->redirectToRoute('app_event_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('event/new.html.twig', [
            'event' => $event,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_event_show', methods: ['GET'])]
    public function show(Event $event): Response
    {
        return $this->render('event/show.html.twig', [
            'event' => $event,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_event_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Event $event, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_event_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('event/edit.html.twig', [
            'event' => $event,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_event_delete', methods: ['POST'])]
    public function delete(Request $request, Event $event, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $event->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($event);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_event_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/event/_delete_form.html.twig
<form method="post" action="{{ path('app_event_delete', { id: event.id }) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
  <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ event.id) }}" />
  <button class="btn btn-danger" style="height: 2.5rem;">Delete</button>
</form>

templates/event/_form.html.twig
{{ form_start(form) }}
{{ form_widget(form) }}
<button class="btn btn-primary my-3">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}
<div clas></div>

templates/event/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  Edit Event
{% endblock %}

{% block body %}
  <h1 class="text-danger">Edit Event</h1>

  {{ include('event/_form.html.twig', { button_label: 'Update' }) }}

  <a href="{{ path('app_event_index') }}" class="btn btn-secondary mb-3">Back to list</a>

  {{ include('event/_delete_form.html.twig') }}
{% endblock %}

templates/event/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  Event index
{% endblock %}

{% block body %}
  <h1 class="my-5 text-danger">Vienna's best events, at your fingertip!</h1>

  <div class="mb-4">
    <form method="get" action="{{ path('app_event_index') }}">
      <div class="form-group">
        <label for="type" class="form-label text-danger">Filter by Event Type:</label>
        <select id="type" name="type" class="form-select" onchange="this.form.submit()">
          <option class="text-danger" value="" {{ app.request.get('type') is null ? 'selected' : '' }}>All</option>
          {% for type in types %}
            <option class="text-danger" value="{{ type.id }}" {{ type.id == app.request.get('type') ? 'selected' : '' }}>{{ type.eventType }}</option>
          {% endfor %}
        </select>
      </div>
    </form>
  </div>

  <div class="row row-cols-lg-3 row-cols-md-2 row-cols-sm-1 row-cols-xs-1 g-4">
    {% for event in events %}
      <div class="col">
        <div class="card h-100 d-flex flex-column">
          <img src="{{ event.image }}" class="card-img-top" alt="Event Image" />
          <div class="card-body d-flex flex-column">
            <h5 class="card-title text-danger">{{ event.name }}</h5>
            <p class="card-text flex-grow-1">{{ event.description }}</p>
            <p class="card-text mb-0">
              <b class="text-danger">Date:</b> {{ event.dateStartTime ? event.dateStartTime|date('Y-m-d H:i:s') : '' }}
            </p>
          </div>
          <div class="card-footer mt-auto d-flex justify-content-around">
            <a href="{{ path('app_event_show', { id: event.id }) }}" class="btn btn-info text-white">Details</a>
            <a href="{{ path('app_event_edit', { id: event.id }) }}" class="btn btn-warning text-white">Edit</a>
            {{ include('event/_delete_form.html.twig') }}
          </div>
        </div>
      </div>
    {% else %}
      <div class="col-12">
        <div class="alert alert-danger text-center" role="alert">No records found</div>
      </div>
    {% endfor %}
  </div>
{% endblock %}

templates/event/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  New Event
{% endblock %}

{% block body %}
  <h1>Create new Event</h1>
  {{ include('event/_form.html.twig') }}

  <a href="{{ path('app_event_index') }}" class="btn btn-secondary">Back to list</a>
{% endblock %}

templates/event/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  Event
{% endblock %}

{% block body %}
  <h1 class="text-center my-4 text-danger">{{ event.name }}</h1>
  <div class="d-flex justify-content-center">
    <div class="card my-3" style="width: 60%;">
      <img src="{{ event.image }}" class="card-img-top" alt="Event Image" />
      <div class="card-body">
        <h5 class="card-title text-danger">Attend {{ event.name }}</h5>
        <p class="card-text">{{ event.description }}</p>
        <p class="card-text">
          <b class="text-danger">Date:</b> {{ event.dateStarttime ? event.dateStarttime|date('Y-m-d H:i:s') : '' }}
        </p>
        <p class="card-text">
          <b class="text-danger">Address:</b> {{ event.address }}
        </p>
        <p class="card-text">
          <b class="text-danger">Capacity:</b> {{ event.capacity }}
        </p>
        <p class="card-text">
          <b class="text-danger">Contact email:</b> {{ event.email }}
        </p>
        <p class="card-text">
          <b class="text-danger">Contact Phone:</b> +{{ event.phonenumber }}
        </p>
        <div class="d-flex justify-content-around">
          <a href="{{ path('app_event_show', { id: event.id }) }}" class="btn btn-info text-white">Details</a>
          <a href="{{ path('app_event_edit', { id: event.id }) }}" class="btn btn-warning text-white">Edit</a>
          {{ include('event/_delete_form.html.twig') }}
          <a href="{{ path('app_event_index') }}" class="btn btn-secondary">Back to list</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}